# This GitHub workflow deploys Bundle assets (ML asset config and more)
# defined under automated_retraining/assets/*
# and automated_retraining/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for automated-retraining Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./automated_retraining

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: automated-retraining-staging-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.210.1
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
